name: Scheduled API Call

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
  schedule:
    - cron: "30 22 * * *" # 22:30 UTC = 06:30 GMT+8

jobs:
  morning-routines:
    name: Morning Routines
    runs-on: ubuntu-24.04
    steps:
      - name: Make an API call
        run: |
          curl -X POST https://api.line.me/v2/bot/message/push \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}" \
          -d '{
              "to": "'"${{ secrets.LINE_GROUP_ID }}"'",
              "messages":[
                  {
                      "type":"text",
                      "text":"早上記得清貓沙、換前後的水盆、確定碗中有兩湯匙飼料哦！"
                  }
              ]
          }'
