name: Scheduled API Call

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
  schedule:
    # - cron: "30 22 * * *" # 22:30 UTC = 06:30 GMT+8
    # - cron: "30 13 * * *" # 13:30 UTC = 21:30 GMT+8
    - cron: "17 3 * * *" # 03:17 UTC = 11:17 GMT+8
    - cron: "27 3 * * *" # 03:27 UTC = 11:27 GMT+8

jobs:
  morning-routines:
    name: Morning Routines
    if: github.event.schedule == '17 3 * * *'
    runs-on: ubuntu-24.04
    steps:
      - run: date
      - name: Make an API call
        run: |
          curl -X POST https://api.line.me/v2/bot/message/push \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}" \
          -d '{
              "to": "'"${{ secrets.LINE_GROUP_ID }}"'",
              "messages":[
                  {
                      "type":"text",
                      "text":"早上記得清貓沙、換前後的水盆、出門前確定碗中有兩湯匙飼料哦！"
                  }
              ]
          }'
  night-routines:
    name: Night Routines
    if: github.event.schedule == '27 3 * * *'
    runs-on: ubuntu-24.04
    steps:
      - run: date
      - name: Make an API call
        run: |
          curl -X POST https://api.line.me/v2/bot/message/push \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}" \
          -d '{
              "to": "'"${{ secrets.LINE_GROUP_ID }}"'",
              "messages":[
                  {
                      "type":"text",
                      "text":"晚上記得清貓沙，睡前碗裡要有兩湯匙飼料，餵1/2罐頭加水給花花！"
                  }
              ]
          }'
