name: Scheduled API Call

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "44 14 * * *"

jobs:
  morning-routines:
    name: Morning Routines
    runs-on: ubuntu-24.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
      - name: test
        run: python --version; python3 --version
      - name: Call API
        run: python morningcall.py
